channels:
  - conda-forge
dependencies:
  - gdal
  - libnetcdf
  - libtiff
  - ncurses
  - numpy
  - pdal
  - ply
  - proj
  - proj
  - python
  - python-dateutil
  - pyyaml
  - readline
  - sqlite
  - termcolor
  - wxpython
  - zstd
