channels:
  - conda-forge
dependencies:
  - gdal
  - git
  - jupyterlab
  - libnetcdf
  - libtiff
  - matplotlib
  - ncurses
  - numpy
  - pandas
  - pdal
  - ply
  - proj
  - python
  - python-dateutil
  - pyyaml
  - readline
  - scikit-learn
  - scipy
  - sqlite
  - termcolor
  - wxpython
  - zstd
