name: CI in VM on Ubuntu

on:
  push:
    paths-ignore:
      - "docs/**"
      - README.md
  pull_request:
    paths-ignore:
      - "docs/**"
      - README.md
  schedule:
    # At 03:30 on Wednesday.
    - cron: "30 3 * * 3"

jobs:
  build:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Get basic dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git build-essential
      - name: Create installation directory
        run: mkdir install
      - name: Set number of cores for compilation
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.HOME }}/conda-env
      - name: Get and compile dependencies
        run: conda create --yes --file environment.yml --prefix $HOME/conda-env
      - name: Set LD_LIBRARY_PATH for GRASS GIS compilation
        run: |
          echo "LD_LIBRARY_PATH=$HOME/conda-env/lib" >> $GITHUB_ENV
      - name: Get and compile GRASS GIS
        run: bash ./compile.sh master $HOME/conda-env $HOME/install
      - name: Add the bin directory to PATH
        run: |
          echo "$HOME/install/bin" >> $GITHUB_PATH
      - name: Basic test of GRASS GIS
        run: bash ./test.sh
      - name: Thorough test of GRASS GIS
        run: bash ./test-thorough.sh
