name: CI in VM on Ubuntu

on:
  push:
    paths-ignore:
      - "docs/**"
      - README.md
      - .cspell.json
  pull_request:
    paths-ignore:
      - "docs/**"
      - README.md
      - .cspell.json
  schedule:
    # At 03:30 on Wednesday.
    - cron: "30 3 * * 3"

jobs:
  build:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - version: master
            command: grass
          - version: releasebranch_7_8
            command: grass78
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Get basic dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git build-essential
      - name: Install dependencies which are on Henry2, so not in conda environment
        run: |
          sudo apt-get install -y \
            flex \
            bison \
            zlib1g-dev \
            libpng-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libfftw3-dev \
            libcairo-dev
      - name: Create installation directory
        run: mkdir install
      - name: Set number of cores for compilation
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
      - name: Set directory for the conda environment
        run: |
          echo "CONDA_PREFIX=$HOME/grass-conda-env" >> $GITHUB_ENV
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: ${{ env.CONDA_PREFIX }}
      - name: Examine the new conda environment
        run: |
          echo "In environment:"
          ls $CONDA_PREFIX
          echo "In environment's bin:"
          ls $CONDA_PREFIX/bin
          echo "In environment's bin - configs:"
          ls $CONDA_PREFIX/bin/*config*
          echo "In environment's include:"
          ls $CONDA_PREFIX/include
          echo "In environment's lib:"
          ls $CONDA_PREFIX/lib
      - name: Set LD_LIBRARY_PATH for GRASS GIS compilation
        run: |
          echo "LD_LIBRARY_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
      - name: Get and compile GRASS GIS
        shell: bash -l {0}
        run: |
          ./compile.sh \
              grass-code \
              https://github.com/OSGeo/grass.git \
              ${{ matrix.version }} \
              $CONDA_PREFIX \
              $HOME/install
      - name: Add the bin directory to PATH
        run: |
          echo "$HOME/install/bin" >> $GITHUB_PATH
      - name: Basic test of GRASS GIS
        shell: bash -l {0}
        run: ./test_quick.sh ${{ matrix.command }}
      - name: Thorough test of GRASS GIS
        shell: bash -l {0}
        run: ./test_thorough.sh ${{ matrix.command }} grass-code .
